### ISSUE TITLE
Mask Format Problem "+"

### ISSUE THREAD

**Issue by andanicalik** [PaXLiCh/FormattEditText#1]
Hi. I implement your library and used MaskedEditText. 

I set inputType:"numberDecimal" and mask:"+\90 (999) 999 99 99". When cursor left of "+", doesn't write numbers. But when cursor right of "+", it's ok. What should I do ?

Thanks for library.

**Comment by PaXLiCh** [comment]
Hi, seems we found a bug. As I understand, you even cant see the character '9' after '+' in start of mask. Can you show video with your problem?

**Comment by andanicalik** [comment]
Now I can't record video, but i will try tell problem again :)

"|+90 (___) ___ __ **" is input in EditText. "|" show cursor and inputType of EditText is "numberDecimal". In this condition, when i select number it doesn't write it. But when i move cursor to right of "+" like "+|90 (_**) ___ __ __) it's okey.

**Comment by PaXLiCh** [comment]
Finally I found how reproduce problem. Now I can recommend to use InputType `number` or `text`. Other variations of InputTypes with flags like `numberSigned` or `numberDecimal` may prevent inputing symbols due to filtering the symbols from mask. In another cases use inputType `text`. Later I commit a workaround to automatic setting of InputType for specified mask. This will help you?

**Comment by andanicalik** [comment]
Thank you for recommendation. I changed inputType to "number" and it's done. Again thank you for your interest. Have a nice day.
